### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by timcappalli** [PhysicalGraph/SmartThings-Alfred#7]
[2017-07-19 00:17:50][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 18, in device_collector
    command = args[-2]
IndexError: list index out of range

**Comment by YayConnolly** [comment]
I also noticed this in the console. The workflow still functions as expected, but I agree it would be good to clean this up.

**Comment by karmajunkie** [comment]
I'm seeing this error, but its not working for me. I'm setting up a new integration to a new smartthings hub (v2), logs look like this: 

```
[2017-09-25 22:53:20][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 18, in device_collector
    command = args[-2]
IndexError: list index out of range
[2017-09-25 22:53:21][input.scriptfilter] <items />
[2017-09-25 22:53:21][input.scriptfilter] <items />
[2017-09-25 22:53:21][input.scriptfilter] <items />
[2017-09-25 22:53:23][input.keyword] Processing output of 'action.script' with arg ''
[2017-09-25 22:53:44][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 18, in device_collector
    command = args[-2]
IndexError: list index out of range
[2017-09-25 22:53:45][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 42, in device_collector
    tokenFile = open("token.txt")
IOError: [Errno 2] No such file or directory: 'token.txt'
[2017-09-25 22:53:45][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 42, in device_collector
    tokenFile = open("token.txt")
IOError: [Errno 2] No such file or directory: 'token.txt'
[2017-09-25 22:53:45][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 42, in device_collector
    tokenFile = open("token.txt")
IOError: [Errno 2] No such file or directory: 'token.txt'
[2017-09-25 22:53:46][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 42, in device_collector
    tokenFile = open("token.txt")
IOError: [Errno 2] No such file or directory: 'token.txt'
[2017-09-25 22:53:46][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 42, in device_collector
    tokenFile = open("token.txt")
IOError: [Errno 2] No such file or directory: 'token.txt'
[2017-09-25 22:53:46][input.scriptfilter] <items><item uid="d3b17a933c2d3dd2dafc47051a8f1264"><icon>icon.png</icon><subtitle>You will be forwarded to https://www.smartthings.com</subtitle><title>Authenticate with SmartThings</title></item></items>
[2017-09-25 22:53:46][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 42, in device_collector
    tokenFile = open("token.txt")
IOError: [Errno 2] No such file or directory: 'token.txt'
[2017-09-25 22:53:48][input.scriptfilter] Processing output of 'action.openurl' with arg ''
[2017-09-25 22:53:48][input.scriptfilter] Processing output of 'action.script' with arg ''
[2017-09-25 22:53:56][ERROR: action.script] 127.0.0.1 - - [25/Sep/2017 22:53:56] "GET /oauth/callback?code=<TOKEN> HTTP/1.1" 301 -
127.0.0.1 - - [25/Sep/2017 22:53:56] "GET /success HTTP/1.1" 200 -
[2017-09-25 22:53:56][action.script] Processing output of 'action.script' with arg 'Starting embedded HTTP server
Processing /oauth/callback?code=TOKEN
Received OAuth callback
Processing /success
Stopping embedded HTTP server
None
'
[2017-09-25 22:53:56][action.script] Processing output of 'output.notification' with arg 'Starting embedded HTTP server
Processing /oauth/callback?code=TOKEN
Received OAuth callback
Processing /success
Stopping embedded HTTP server
None
'
[2017-09-25 22:54:49][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "device_collector.py", line 18, in device_collector
    command = args[-2]
IndexError: list index out of range
[2017-09-25 22:54:49][input.scriptfilter] <items />
[2017-09-25 22:55:00][input.scriptfilter] <items />
[2017-09-25 22:55:02][input.keyword] Processing output of 'action.script' with arg ''
[2017-09-25 22:55:02][ERROR: action.script] Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "refresh_devices.py", line 28, in refresh_devices
    response = urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
[2017-09-25 22:55:02][action.script] Processing output of 'output.notification' with arg ''
```

**Comment by karmajunkie** [comment]
Actually nevermind—I somehow downloaded an older version of this workflow. The current version seems to be working properly.
